### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by sg3des** [tbogdala/cubez#1]
1. why in cubez you use `type Real float64`, instead just float64?
2. your engine [fizzle](https://github.com/tbogdala/fizzle) use `mgl32.Vec3` for vectors, and cubez `.../cubez/math.Vector3` - what is the reason? it is possible to standardize?

**Comment by tbogdala** [comment]
It's not a bad question at all.

It would seem like the common perception is that `Real` in cubez should be defined as float32 by default. At present, as you've noted, it is not. (Note: You can always clone and redefine Real as float32 if it is needed by you.)

Why did I do this? I guess by default I wanted max precision and it becomes the client's choice to lower precision to float32 if that's what the use case needs. I was curious if float64 would really cause any performance drops.

Either way, I haven't yet done the benchmarks yet. And at this point in time, at this early hour of the morning for me, I don't feel strongly compelled either way to float32 or float64.
